[package]
name = "actix-casbin-example"
version = "0.1.0"
authors = ["Chojan Shang <psiace@outlook.com>"]
edition = "2018"

[dependencies]
ntex = "0.1.7"
casbin = "0.4"
loge = { version = "0.4", default-features = false, features = ["colored", "chrono"] }
