[package]
name = "rustls-example"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "rustls-server"
path = "src/main.rs"

[dependencies]
env_logger = "0.7"
rustls = "0.17"
ntex = { version = "0.1.7", features = ["rustls"] }
ntex-files = "0.1.0"
