[package]
name = "template_yarte"
version = "0.0.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
ntex = "0.1.7"
env_logger = "0.7"
yarte = { version = "0.7", features = ["with-actix-web"]  }

[build-dependencies]
yarte = { version = "0.7", features = ["with-actix-web"]  }
